### ISSUE TITLE
Plugin ainda funcional?

### ISSUE THREAD

**Issue by marcos-alexandre82** [Datadev/datadev-total-express-for-woocommerce#1]
Olá, 

Parabéns pelo plugin! Sabe me dizer se ele ainda funciona com a versão mais atual do WooCommerce? Porque removeu ele do repositório oficial de plugins?

Att,

**Comment by skydogtk** [comment]
Olá @marcos-alexandre82 
O plugin continua funcionando com a versão atual (4.3.0).
Sobre o repositório, resolvemos usar por um tempo antes de submeter e acabou nunca sendo submetido (mas pretendemos fazer isso em breve).

Atenciosamente,

**Comment by skydogtk** [comment]
BTW,

O plugin foi submetido:
https://wordpress.org/plugins/datadev-total-express-for-woocommerce/

**Comment by marcos-alexandre82** [comment]
@skydogtk show!
